# A guide to open source hardware projects

This book presents explanations for elements of the hardware documentation template. The documentation should grow with the project size, and should not limit itself to the technical aspects of the hardware (how to rebuild it), but should present the project in its entirety, such that new users and new collaborators can find the information they need to participate in the project.

The book chapters follows the different elements of the template (readme,community, project history, product development, product build / production, and user guides). In addition the firsts chapters present the steps proposed for the development of the project (ideation, needs analysis, concept development, prototype, replication), linking to the sections relevant for that development step.

Note_1: hardware development starts only in step four, the preparation phase is important if one does not want to end up reinventing the wheel of producing useless hardware.
Note_2: Step 1-3 have an iterative nature: Especially, the analysis of "Similar projects" coming in step 3, and the prototyping (step 4) are often giving new ideas and refining use cases.

This is a quarto book, each element having its own quarto/markdown file.