---
editor: 
  markdown: 
    wrap: 72
---

# Readme as entry door

Think about your audience when writing OSH documentation. Indeed, your
project might be reused by people with different skills, roles,
objectives, and socio-economic and cultural environments. Because of
this it can be useful to create a list of skills that are required to
build (manufacture @sec-product-build-manufacturing-all, and assemble
@sec-product-build-assembly-skills-and-tools) or use the hardware
(@sec-user-skills). Someone trying to build it from scratch, for
example, will require specific set of prior knowledge, skills, and
tools. A different set is needed to perform maintenance tasks. An end
user operating the assembled project might require an entirely distinct
skillset (and documentation).

## Vision and motivation {#sec-vision-and-motivation}

The vision provides details about the project ultimate goal, its
specificity and main objectives, it answers the question:

> What, for whom and why do we have this project ?

It serves to give meaning to the whole endeavor and is a representation
of what we want to achieve. It may also present the problem the project
aims at solving.

It addresses the question: Why are you starting this project?

Examples:

> OpenFlexure (https://openflexure.org)
>
> The OpenFlexure project makes high precision mechanical positioning
> available to anyone with a 3D printer - for use in microscopes,
> micromanipulators, and more.

> Pedal-powered toolkit for fablab
> (https://codeberg.org/openmakeXlowtech/PedalPoweredMachine-4fablab)
>
> This projects aims at providing fablabs and makerspaces with pedal
> powered toolkit, in order to open discussions around the principles of
> [low technologies](https://en.wikipedia.org/wiki/Low_technology):
> especially questioning needs (do we need the object), and designing
> while recognizing the ecological impact (choice of material, improving
> durability and repairability).
>
> One single pedal "motor" will be connected with several tools usually
> requiring a rotating motor (sewing machine, saw, ...). The main goal
> is to question the use of electrical power and show the simplicity of
> the tool in fablabs. The multi-functionality is important for the
> concept of sufficiency (less resources for a similar output). An
> additional goal may be to enhance collaborative work (one need two
> people to use the tools).
>
> We think this may also help solves the problem of "building fancy but
> useless objects" we sometimes see in fablabs, when objects are build
> to show one's skill and the possibilities of the machines, but they do
> not answer any needs.

> BCN3D
>
> The project BCN3D Moveo is motivated by the high cost of the materials
> that undergraduate students must use for learning how to engineer
> mechatronics systems.

------------------------------------------------------------------------

**Sources**

@sec-open-next-work, @sec-source-turing
