# product dvt - architectural structure

This section will give an overview of the structural model, while details are given in the specific mechanical (), electrical () and software () architectures sections.

## Structural model

The Structural model explains the physical structure of the product and its components, it is:

  
* A description of the components (the combination of parts) of a product and their relationships.
* An opportunity to specify the geometric elements, dimensions, topology, and other physical properties of the product.
* The potential solutions (concepts), which are the result of the conceptual design phase.
* The set of mechanics theories that obey physical laws required to study and predict the behavior of structures.

## Why should you define structural model?

* A structural model helps to describe the geometric elements (design feature, dimensions, constraints, etc.), topology (assembly constraint between components, tolerances, components mating conditions, etc.), and characteristics of the product.
* A structural model helps to decide the physical form of the product and its components to ensure that the structure is fit for its intended purpose. 
* Structural model provides users with a physical model of the product, components, and characteristics of the material at the design phase that enable the stakeholder to understand the geometry, material reaction to external factors, etc.
* The structural model ensures that the structures are safe and fulfill the functions for which they were built.

