## Software and Firmware architecture {#sec-software-and-firmware-architecture}

The software architecture represents the repository details of all the software and firmware that is necessary for reusing and running the project.
Indicate how the different software depend on each other. 

It might be interesting to describe the data flow and its format.

See @sec-structural-model for information about how to document this.
Provide both an image and the editable files, as well as instruction how to use them.


### Software and Firmware details

Please provide :

-   Clear installation guide
-   Description of programming algorithm
-   The source code
-   Version of software and its dependencies (both hardware and software dependencies)

### Documentation of different parts of software 

> Examples:
>
> [Nasa-JPL](https://github.com/nasa-jpl/open-source-rover/tree/master/software)\*
>
> [AmboVent](https://github.com/AmboVent-1690-108/AmboVent/tree/master/3-Software)\*
>
> [Poppy project](https://docs.poppy-project.org/en/installation/)\*

------------------------------------------------------------------------

**Sources**

@sec-open-next-work
