# Project history

## Changelog {#sec-project-history-changelog}

A changelog is a plain text file that contains a record of what *notable* changes are made between versions of hardware. It includes new features, enhancements, bug fixes, and even minor tweaks.
The [**keep a changelog**](https://keepachangelog.com/en/1.1.0/) website provides a detailed explanation of what a change log is (in the software case).

Changelogs are primarily intended for technical contributors and power users who need a detailed understanding of how the hardware has evolved over time.



**Guiding Principles**

- Changelogs are for humans, not machines.
- There should be an entry for every single version.
- The same types of changes should be grouped.
- Versions and sections should be linkable.
- The latest version comes first.
- The release date of each version is displayed.
- Mention whether you follow Semantic Versioning.
- Types of changes:

    - Added for new features.
    - Changed for changes in existing functionality.
    - Deprecated for soon-to-be removed features.
    - Removed for now removed features.
    - Fixed for any bug fixes.
    - Security in case of vulnerabilities.

------------------------------------------------------------------------

**Sources**

@sec-source-turing, https://keepachangelog.com/en/1.1.0/
