# Maintenance {#sec-maintenance}

Maintenance instructions provide the necessary information to maintain the system effectively and perform the required operations to system works properly in the long run.
This includes advice on the frequency of the maintenance and the risks of failure.

It may also include information on the process of modifying a system or component after delivery, in order to correct faults, improve performance or other attributes, or adapt to a changing environment.

## Maintenance instructions

A maintenance instruction is a technical communication document intended to give recommendations and necessary information to maintain the system effectively.
In this book, we treat the identification of defective components and their repair as separate tasks, while others have defined it as part of the maintenance.

Note that the instructions are meant for the users and should therefore be focused on the schedule of maintenance.
The maintenance information (what to do) may be directed toward experienced/professional people.
In addition, this latter (technical) information may be best linked to the technical documentation of each part, in order to avoid giving outdated information (for example giving repair information for version 1, while the rest of the documentation is for version 2 of a hardware).

The maintenance user guide may include:

1.  Introduction of general maintenance
    -   Cleaning
    -   Lubricating
    -   Regular inspections or services. These can be carried out on a time-based schedule or a usage-based schedule. See also @sec-user-guides-repair:
        -   Maintenance according to predetermined intervals
        -   Maintenance according to prescribed criteria
        -   Maintenance by integrating analysis, measurement, and periodic test activities
    -   Regular adjusting machinery 
    -   Maintenance tools (Various tools necessary to perform the maintenance operation)
    -   Schedule for Replacing equipment, see also @sec-user-guides-replacing-equipment-components

> examples [FarmBot Genesis V1.5](https://genesis.farm.bot/v1.5/Extras/maintenance)

### Template of maintenance


Common procedures:
  - cleaning
  - lubricating
  - machine adjustments
  - calibrations
  - (periodic) test activities
  
Information to give:
  - predetermined interval
  - prescribed criteria
  - tools
  - verification procedure

------------------------------------------------------------------------

**Sources**

OpenNext work project resutls: @sec-open-next-work
