## Disposal instructions {#sec-disposal-instructions}

Disposal instructions identify the process of removing a system or its component, ensuring the proper handling of any environmentally sensitive materials, and sending the remainder to surplus storage or sale.

They describe each component with information about their end of life (depending on their material content).
Each element will be classed corresponding to their "recyclability", and information is given to reduce the negative environmental impact of the disposal and recycling of the hardware component.

### Template of disposal instruction

For each element or part, indicate:

-   sub-part name

-   parent part number and name, with links

-   link to dissassembly instructions (see @sec-disassembly)

-   material used + how many times can it be recycled (see also @sec-component-lifespan)

-   recyclable (yes/no/conditional, see @sec-classing-elements )

-   disposition information, for each option:

    -   how to dispose
    -   environmental assessment of disposal options (\@sec-environmental-assessment):
        -   described the negative consequences of disposal
        -   Define and describe the main parameters and processes to decrease these negative environmental impacts

-   end of life information

### Classing elements {#sec-classing-elements}

There are different types of elements:

-   Recyclable: waste wich can be turn into another form of new and reusable materials without specific treatment.

-   Non-recyclable: the components or products that design for single-use, which means they get discarded immediately after use.

-   Conditionally recyclable: component which needs specific treatment before being recycled.

Usual workflow for disposition:

-   Distinguishing the recyclable, Conditionally recyclable and Non-recyclable components or products.
-   Determining what material can recycle many times
-   Identify the product lifespan for disposing and/or recycling.
-   Describe how to recycle the components or products and their type of materials?
-   Describe how to dispose of components which cannot be recycled.

Disposable products are most often made from Polystyrene and Cotton, Non-recyclable products from Textiles and Ceramics.

### Types of disposal:

-   Incineration: This type of waste disposal involves the dumping off method where you eliminate waste materials via combustion.
-   Landfill: It involves collecting, transporting, dumping, and burying waste in a designated land.

### Environmental assessment {#sec-environmental-assessment}

It is the assessment of the environmental consequences of disposing or recycling a product before the decision to move forward with the proposed action.
Indicate:

\- The negative consequences of disposable products on the environment if sustainability isn't factored into disposal options.

\- How to select the disposal or recycling process to have a less environmental impact?

### 

**Sources**

@sec-open-next-work
