## Product development and CAD files

Computer assisted design is usually used to create structures from the models. The designs should be best provided in their raw format (Native formats), an editable standard format (Neutral formats), and a exported format used for manufacture. For example, a fusion .f3d file, a Step file and a STL file.

### CAD for electronics, PCB design

To reuse a electrical design, it should provide information consist of:

1.  Preferable file format

-   Editable file formats that could be:
    -   Source formats such as .gbr, .lib format\
    -   Neutral formats such as Kicad_mod, kicad_pcb

2.  Preferable open-source software

-   Tiny CAD
-   KiCAD
-   ADINA

> Examples:
>
> [Nasa-JPL, source files](https://github.com/nasa-jpl/open-source-rover/tree/master/electrical/pcb/arduino_uno_sheild/gerbers/rev_b)\*
>
> [AmbovVent, Neutral files](https://github.com/AmboVent-1690-108/AmboVent/tree/master/1-Electronics)\*


### CAD for structure models

Model design should be provided in a format that can be used to manufacture each piece: usually STL and STEP file for 3D objects, and SVG file for 2D design, electrical design can be shared in the editable format directly. These formats are often easier to preview, and will help understand the structural/electrical design.

Note that the file is often not sufficient to reproduce one piece and manufacturing information must be given, as explained in @sec-product-build-manufacturing-instructions.


### Editable file format 

 
An editable file format is a standard way that information is encoded for storage and allows the makers to study, modify the geometry of a model and reuse it.

To reuse a design model, it should provide information consist of:

 1. Preferable 3D/2D file format
   - Editable file formats that could be:
     - Native formats such as .FCStd format of FreeCAD 
     - Neutral formats such as STEP files
 2. Preferable open-source software 
   - OpensCAD
   - Inkscape
   - FreeCAD



 
> Example of editable file formats:
>
> - [Farmbot, Native CAD files](https://genesis.farm.bot/v1.5/Extras/cad)*
>
> - [MIT Emergency Ventilator, Neutral CAD files](https://e-vent.mit.edu/resources/downloads/)*
>
> - Types of CAD format of [transmagic](https://transmagic.com/cad-formats/)*

 ------------------------------------------------------------------------

**Sources**

@sec-open-next-work


 


