## Community - Governance {#sec-community-governance}

Provide a decision-making framework to facilitate discussions and reaching a shared conclusion.
In the context of software and hardware, open source projects are often as much about communication as they are about coding or building (if not more).
Allow informed discussions when a particular project design has reached the end or when it is useful to update it for efficiency and sustainability.

A leadership structure in an open project should aim to empower others and develop agency and accountability in your community.
You can start by listing different tasks within your project and inviting your members to lead those tasks.
Provide appropriate incentives and acknowledgment for the contributions made by your community members.
Create opportunities for members to share some leadership responsibilities with you in the project.
When inviting suggestions and ideas from the community, provide the first set of plans where your community can develop from.

See https://opensource.guide/leadership-and-governance/ for more information.

------------------------------------------------------------------------

**Sources**

@sec-source-turing
