## Step 2 Specification, Needs analysis 

### Needs and ecosystem analysis

Using a open source hardware canva to analyse the project may be useful at this point (defining users, contributors, communication channels, resources required).

A lot of the user analysis and the problem description part aims at the definition of the constrains and requirements for the hardware which is included in the product development part of the documentation.

It may also be time to work on community engagement.

### Checklist specifications

-   [ ] Complete the readme file
    -   [ ] development stage: needs analysis
    -   [ ] *ethics statement (human/animal use or Informed Consent Statement)* @sec-ethics-statement
    -   [ ] *competing interest* @sec-competing-interest
    -   [ ] future work (@sec-future-work), roadmap (@sec-roadmap)
    -   [ ] *Project history summary* @sec-project-history-summary
    -   [ ] longer problem description @sec-problem-description
    -   [ ] Documentation structure @sec-documentation-structure
-   [ ] Contributions
    -   [ ] Contribution guidelines @sec-community-guidelines
    -   [ ] work culture that you want to promote @sec-community-work-culture
    -   [ ] Code of conduct @sec-community-code-of-conduct
    -   [ ] Governance @sec-community-governance
-   [ ] User analysis (this can be a personas analysis)
    -   [ ] Ecosystem analysis (`stakeholder`) @sec-diverse-actors-and-ecosystem
    -   [ ] target groups (who will use the product) @sec-user-analysis-target-groups
    -   [ ] External interfaces (how will they use the product) @sec-user-analysis-external-interfaces
    -   [ ] skills needed to use @sec-user-skills
-   [ ] Product development
    -   [ ] requirements @sec-product-development-requirements
    -   [ ] constrains @sec-product-dev-constrains
    -   [ ] capability @sec-productdvt-capability
-   [ ] History
    -   [ ] *changes log* @sec-project-history-changelog
