## Step 4: product development and prototyping 

### Prototyping

Here the work on the design starts! Continuous documentation of choice made, successes and failuress are welcome, so this step has an iterative components: with every development can come specific documentation.

In addition, the documentation may need to be performed for different parts (or modules) of the hardware.

Importantly, the Product design, manufacturing and assembling instruction may be organised using different strategies. Some projects may write simple text files like the rest of the documentation; other projects may using Gitbuilding to write the assembly instruction, and deriving the bill of material from it; other projects may derive assembly instructions from their CAD files.

This step is also divided in two: a preparatory phase defining the main components and an iterative phase which can change with the different version of the hardware.


### Checklist 4a: preparations

- [ ] Complete the readme file
  - [ ] development stage: prototyping
  - [ ] Standard compliance @sec-standard-compliance
  - [ ] Product outputs (if relevant: data outputs) @sec-outputs-products-and-data
  - [ ] Citing information @sec-cite-this-project

  
- [ ] Product development
  - [ ] Structural architecture
    - [ ] Mechanical architecture @sec-mechanical-architecture
    - [ ] Software/firmware architecture @sec-software-and-firmware-architecture
    - [ ] Electrical design architecture @sec-electrical-architecture

### Checklist 4b: iteration of design
- [ ] Complete the readme file
  - [ ] Update Documentation structure 

- [ ] Product design
  - [ ] Bill of material @sec-product-build-bill-of-material
  - [ ] material characteristics @sec-product-build-material-characteristics
  - [ ] electrical design @sec-product-buildelectrical-design
  - [ ] Software: Documentation of different parts @sec-product-build-firmwaresoftware
  
- [ ] Manufacturing instructions  
    - [ ] Manufacturing skills and tools @sec-product-build-manufacturing-skills, @sec-product-build-manufacturing-tools
    - [ ] Manufacturing sequences and instruction @sec-product-build-manufacturing-instructions
    
- [ ] Assembly instructions
  - [ ] assembly skills and tools @sec-product-build-assembly-skills-and-tools
  - [ ] Safety information @sec-safety-instruction-assembly
  - [ ] Assembly sequence and instruction @sec-product-build-assembly-instructions

- [ ] User guide
  - [ ] Safety information @sec-user-guides-safety-information
  - [ ] overview of the hardware @sec-user-guides-overview-of-the-hardware
  - [ ] Operation instructions @sec-operation-instructions
  - [ ] Testing instructions and troubleshooting @sec-user-guides-troubleshooting
  - [ ] basic maintenance + schedule @sec-maintenance
  - [ ] basic disposal @sec-disposal-instructions
  
- [ ] History  
  - [ ] update changelog/release note
  - [ ] update design choice history

