## Step 5: replicator step

### Replication and maturation

Here the prototype is mature enough that it should be replicated in different places. While most of the work was already present at step 4, here we go into more quality and details.

### Checklist replication

- [ ] Complete the readme file
  - [ ] development stage: replication ready
  - [ ] scientific publication @sec-scientific-publication
  - [ ] education resources @sec-education-resources
  - [ ] Institutional Review Board Statement @sec-institutional-review-board-statement
  - [ ] discussions @sec-discussions
  - [ ] validation @sec-validation
  - [ ] cost 
  
- [ ] Assembly instructions
  - [ ] disassembly instructions @sec-disassembly

- [ ] Product design
  - [ ] component lifespan @sec-component-lifespan
  
- [ ] User guide
  - [ ] Environmental management @sec-user-guidesenvironmental-management
  - [ ] Maintenance @sec-maintenance 
      - [ ] Instructions @sec-maintenance-instructions
      - [ ] Schedules @sec-maintenance-schedules
      - [ ] Summary component lifetime or links @sec-component-lifespan
  - [ ] Repair @sec-user-guides-repair
      - [ ] Identifying the defective components @sec-identifying-the-defective-components
      - [ ] Repairing the defective components @sec-repairing-the-defective-components  
      - [ ] Replacing equipment components @sec-identifying-the-defective-components      



